#!/bin/sh
export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
sudo npm install --production
killall node
sleep 10s
BUILD_ID=dontKillMe node server.js &
exit
